version: "2.2"
services:
  backend:
    build:
      context: ./
      target: release
    environment:
      - RUST_LOG=debug
      - CONN_URI=mongodb://root:example@mongo
      - LOG_FILE=/var/log/routedatacollect/server_log.txt
    env_file:
      - ./routedatacollect/api.env
    networks:
      - server-side
    volumes:
      - ./routedatacollect/src:/code/routedatacollect/src
      - ./routedatacollect/google_protos:/code/routedatacollect/google_protos
      - ./job_scheduler/src:/code/job_scheduler/src
      - backend-cache:/code/target
      - logs:/var/log/routedatacollect/
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - server-side
    volumes:
      - mongo:/data

networks:
  server-side: {}

volumes:
  backend-cache: {}
  logs: {}
  mongo:
    driver: local
