name: route
services:
  backend:
    build:
      context: ./
      target: builder
    environment:
      - RUST_LOG=info
      - CONN_URI=mongodb://root:example@mongo
    env_file:
      - ./route_data_collect/api.env
    networks:
      - server-side
    volumes:
      - ./route_data_collect/src:/code/route_data_collect/src
      - ./route_data_collect/google_protos:/code/route_data_collect/google_protos
      - ./job_scheduler/src:/code/job_scheduler/src
      - backend-cache:/code/target
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - server-side
    volumes:
      - mongo:/data
    tty: true

networks:
  server-side: {}

volumes:
  backend-cache: {}
  mongo:
    driver: local
